#!/bin/bash

source ../libs.sh

rm -rf $BUILD_DIRECTORY &&\
mkdir $BUILD_DIRECTORY &&\
cd $BUILD_DIRECTORY &&\
cmake   -D WITH_TBB=ON -D TBB_INCLUDE_DIRS=$INCLUDE_DIR -D TBB_LIB_DIR=$LIBRARY_DIR \
        -D WITH_EIGEN=ON -D EIGEN_INCLUDE_PATH=$INCLUDE_DIR/eigen3 \
	-D WITH_QT=ON \
        -D INSTALL_PYTHON_EXAMPLES=ON -D WITH_IPP=ON \
        -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=$INSTALL_DIR \
        -D CMAKE_TOOLCHAIN_FILE=$CMAKE_TOOLCHAIN \
        -D CMAKE_PREFIX_PATH=$CMAKE_LIB_DIR \
        ..

