#!/bin/bash

source ../libs.sh

rm -rf $BUILD_DIRECTORY &&\
mkdir $BUILD_DIRECTORY &&\
cd $BUILD_DIRECTORY &&\
cmake   -D WITH_TBB=ON -D TBB_INCLUDE_DIRS=$TBB_INCLUDE_DIR -D TBB_LIB_DIR=$TBB_LIB_DIR \
        -D WITH_EIGEN=ON -D EIGEN_INCLUDE_PATH=$EIGEN_INCLUDE_DIR \
        -D WITH_QT=ON \
        -D INSTALL_PYTHON_EXAMPLES=ON -D WITH_IPP=ON \
        -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=$OPENCV_INSTALL_DIR \
        -D CMAKE_TOOLCHAIN_FILE=$HOME/rpi-toolchain.cmake \
        -D CMAKE_PREFIX_PATH=$QT_INSTALL_DIR/lib/cmake \
        ..

